const fs = require("fs");

// Your current array with variable names (the "bad" data)
const rawData = [
  {
    id: "0009",
    author: "Murakami",
    title: "After Dark",
    comments: 5,
    people: 100,
    price: "$15.5",
    saleP: "$10.50",
    type: "novel",
    publishDate: "May 2007",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: "Rib Knits",
  },
  {
    author: "Murakami",
    title: "After Dark",
    comments: 5,
    star: 3.0,
    people: 100,
    price: "$15.5",
    saleP: "$10.50",
    type: "novel",
    publishDate: "May 2007",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: "Rib Knits",
  },
  {
    author: "Mario Puzo",
    title: "The Godfather",
    comments: 15,
    star: 4.9,
    people: 85,
    saleP: "$14.50",
    type: "novel",
    publishDate: "May 2007",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: "Rib Knits",
  },
  {
    author: "Daniel Cargallo",
    title: "She Beyond Sun",
    comments: 14,
    star: 4.6,
    people: 165,
    price: "$19.50",
    saleP: "$15.00",
    type: "novel",
    publishDate: "May 2007",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: "Panne Velvet",
  },
  {
    author: "Erik Spiekermann",
    title: "Hello I am Erik",
    comments: 25,
    star: 4.5,
    people: 120,
    price: "$15.50",
    saleP: "$10.50",
    type: "novel",
    publishDate: "May 2007",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: "Elasticized Fabrics",
  },
  {
    author: "Patrick Ness",
    title: "More Than This",
    comments: 42,
    star: 4.4,
    people: 48,
    saleP: "$20.00",
    type: "novel",
    publishDate: "May 2007",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: " Dotted Swiss",
  },
  {
    author: "Erik Spiekermann",
    title: "Hello I am Erik",
    comments: 25,
    star: 4.5,
    people: 120,
    price: "$15.50",
    saleP: "$10.50",
    type: "novel",
    publishDate: "May 2007",
    language: "Russian",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: " Dotted Swiss",
  },
  {
    author: "Patrick Ness",
    title: "More Than This",
    comments: 42,
    star: 4.4,
    people: 48,
    saleP: "$20.00",
    type: "novel",
    publishDate: "May 2006",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: "Elasticized Fabrics",
  },
  {
    author: "C.R. Brunt",
    title: "From the Memoirs of a Non-Enemy",
    comments: 25,
    star: 4.5,
    people: 120,
    saleP: "$16.50",
    type: "novel",
    publishDate: "May 2007",
    language: "Russian",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: "Elasticized Fabrics",
  },
  {
    author: "Mikhail Bulgakov",
    title: "The Master & Margarita",
    comments: 35,
    star: 4.0,
    people: 30,
    saleP: "$10.50",
    type: "novel",
    publishDate: "May 2007",
    language: "Russian",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: "Panne Velvet",
  },
  {
    author: "Donald Norman",
    title: "The Design of Everyday Things",
    comments: 28,
    star: 3.2,
    people: 20,
    saleP: "$9.50",
    type: "novel",
    publishDate: "May 2005",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Softcover",
    publisher: "Panne Velvet",
  },
  {
    author: "Erik Spiekermann",
    title: "Hello I am Erik",
    comments: 25,
    star: 4.5,
    people: 120,
    price: "$15.50",
    saleP: "$10.50",
    type: "novel",
    publishDate: "May 2008",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Softcover",
    publisher: "Panne Velvet",
  },
  {
    author: "Patrick Ness",
    title: "More Than This",
    comments: 42,
    star: 2.4,
    people: 48,
    saleP: "$20.00",
    type: "novel",
    publishDate: "May 2006",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Softcover",
    publisher: "Double Knit",
  },
  {
    author: "Erik Spiekermann",
    title: "Hello I am Erik",
    comments: 25,
    star: 4.5,
    people: 120,
    price: "$15.50",
    saleP: "$10.50",
    type: "novel",
    publishDate: "May 2007",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: "Elasticized Fabrics",
  },
  {
    author: "Haruki Murakami",
    title: "After Dark (Standard)",
    comments: 12,
    star: 4.2,
    people: 210,
    price: "$18.00",
    saleP: "$12.99",
    type: "Mystery",
    publishDate: "May 2007",
    language: "English",
    pages: 208,
    readTime: "5 hours",
    cover: "Hardcover",
    publisher: "Vintage Books",
  },
  {
    author: "Mario Puzo",
    title: "The Godfather: Legacy",
    comments: 85,
    star: 4.9,
    people: 1200,
    price: "$22.50",
    saleP: "$14.50",
    type: "Crime",
    publishDate: "March 1969",
    language: "English",
    pages: 448,
    readTime: "12 hours",
    cover: "Paperback",
    publisher: "Putnam",
  },
  {
    author: "D. Cargallo",
    title: "Beyond The Sun",
    comments: 22,
    star: 4.6,
    people: 165,
    price: "$19.50",
    saleP: "$15.00",
    type: "Sci-Fi",
    publishDate: "June 2015",
    language: "Spanish",
    pages: 310,
    readTime: "8 hours",
    cover: "Digital",
    publisher: "Galaxia",
  },
  {
    author: "Erik Spiekermann",
    title: "Typography Mastery",
    comments: 45,
    star: 4.8,
    people: 340,
    price: "$45.00",
    saleP: "$38.00",
    type: "Design",
    publishDate: "Jan 2014",
    language: "German",
    pages: 250,
    readTime: "4 hours",
    cover: "Hardcover",
    publisher: "Gestalten",
  },
  {
    author: "Patrick Ness",
    title: "The Chaos Walking",
    comments: 104,
    star: 4.7,
    people: 890,
    price: "$25.00",
    saleP: "$20.00",
    type: "YA Fiction",
    publishDate: "Sept 2008",
    language: "English",
    pages: 400,
    readTime: "10 hours",
    cover: "Softcover",
    publisher: "Walker Books",
  },
  {
    author: "C.R. Brunt",
    title: "The Non-Enemy Memoirs",
    comments: 8,
    star: 3.9,
    people: 45,
    price: "$16.50",
    saleP: "$14.00",
    type: "Biography",
    publishDate: "Nov 2020",
    language: "Russian",
    pages: 512,
    readTime: "15 hours",
    cover: "Hardcover",
    publisher: "Siberian Press",
  },
  {
    author: "M. Bulgakov",
    title: "Margarita's Secret",
    comments: 67,
    star: 5.0,
    people: 400,
    price: "$15.00",
    saleP: "$10.50",
    type: "Classic",
    publishDate: "Original 1967",
    language: "Russian",
    pages: 384,
    readTime: "9 hours",
    cover: "Hardcover",
    publisher: "YMCA Press",
  },
  {
    author: "Don Norman",
    title: "Psychology of Objects",
    comments: 200,
    star: 4.9,
    people: 5000,
    price: "$20.00",
    saleP: "$16.20",
    type: "Non-Fiction",
    publishDate: "Oct 1988",
    language: "English",
    pages: 352,
    readTime: "7 hours",
    cover: "Softcover",
    publisher: "Basic Books",
  },
  // REPEATING IMAGES WITH NEW DATA
  {
    author: "H. Murakami",
    title: "After Dark: Special Ed.",
    comments: 3,
    star: 3.5,
    people: 12,
    price: "$30.00",
    saleP: "$25.00",
    type: "Limited",
    publishDate: "May 2024",
    language: "Japanese",
    pages: 210,
    readTime: "5 hours",
    cover: "Leatherbound",
    publisher: "Shinchosha",
  },
  {
    author: "Mario Puzo",
    title: "The Sicilian Connection",
    comments: 12,
    star: 4.1,
    people: 90,
    price: "$14.00",
    saleP: "$11.00",
    type: "Crime",
    publishDate: "1984",
    language: "Italian",
    pages: 400,
    readTime: "11 hours",
    cover: "Softcover",
    publisher: "Random House",
  },
  {
    author: "Patrick Ness",
    title: "More Than This",
    price: "$14",
    comments: 42,
    star: 4.4,
    people: 48,
    saleP: "$20.00",
    type: "novel",
    publishDate: "May 2007",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: " Dotted Swiss",
  },
  {
    author: "Erik Spiekermann",
    title: "Hello I am Erik",
    comments: 25,
    star: 4.5,
    people: 120,
    price: "$15.50",
    saleP: "$10.50",
    type: "novel",
    publishDate: "May 2007",
    language: "Russian",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: " Dotted Swiss",
  },
  {
    author: "Patrick Ness",
    title: "More Than This",
    comments: 42,
    star: 4.4,
    people: 48,
    saleP: "$20.00",
    type: "novel",
    publishDate: "May 2006",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: "Elasticized Fabrics",
  },
  {
    author: "C.R. Brunt",
    title: "From the Memoirs of a Non-Enemy",
    comments: 25,
    star: 4.5,
    people: 120,
    saleP: "$16.50",
    type: "novel",
    publishDate: "May 2007",
    language: "Russian",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: "Elasticized Fabrics",
  },
  {
    author: "Mikhail Bulgakov",
    title: "The Master & Margarita",
    comments: 35,
    star: 4.0,
    people: 30,
    saleP: "$10.50",
    type: "novel",
    publishDate: "May 2007",
    language: "Russian",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: "Panne Velvet",
  },
  {
    author: "Donald Norman",
    title: "The Design of Everyday Things",
    comments: 28,
    star: 3.2,
    people: 20,
    saleP: "$9.50",
    type: "novel",
    publishDate: "May 2005",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Softcover",
    publisher: "Panne Velvet",
  },
  {
    author: "Erik Spiekermann",
    title: "Hello I am Erik",
    comments: 25,
    star: 4.5,
    people: 120,
    price: "$15.50",
    saleP: "$10.50",
    type: "novel",
    publishDate: "May 2008",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Softcover",
    publisher: "Panne Velvet",
  },
  {
    author: "Patrick Ness",
    title: "More Than This",
    comments: 42,
    star: 2.4,
    people: 48,
    saleP: "$20.00",
    type: "novel",
    publishDate: "May 2006",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Softcover",
    publisher: "Double Knit",
  },

  // ... add your other objects here
];

const cleanedData = rawData.flat().map((book) => ({
  title: book.title || "Unknown Title",
  title: book.title || "Unknown Title",
  author: book.author || "Unknown Author",
  price: String(book.price || book.saleP), // Ensure it's a string
  saleP: String(book.saleP),
  type: book.type || "novel",
  publishDate: String(book.publishDate),
  language: book.language || "English",
  readTime: book.readTime || "N/A",
  cover: book.cover || "Softcover",
  publisher: book.publisher || "Unknown Publisher",
  pages: Number(book.pages) || 0, // Ensure it's a number
  comments: Number(book.comments) || 0,
  reviewNum: Number(book.star) || 0, // Mapping 'star' to 'reviewNum'
  peopleReviewed: Number(book.people) || 0,
}));

fs.writeFileSync("CLEANED_DATA.json", JSON.stringify(cleanedData, null, 2));
console.log("Data cleaned and saved to CLEANED_DATA.json");
