import AfterDark from "../assets/images/Murakami.png";
import Norman from "../assets/images/dNorman.png";
import BeyondTheSun from "../assets/images/beyondTheSun.png";
import Godfather from "../assets/images/godfather.jpeg";
import IAmErik from "../assets/images/IAmErik.png";
import Master from "../assets/images/master.png";
import Ness from "../assets/images/ness.png";
import Memoirs from "../assets/images/memoirs.png";

import Fyodor from "../assets/images/Fyodor-Dostoyevskiy.jpg";
import Erik from "../assets/images/Erik-Spiekermann.png";
import Zola from "../assets/images/ZolaNeale.jpg";
import Don from "../assets/images/Don-Norman.jpg";
import JK from "../assets/images/JK-Rowling.jpg";
import Matthew from "../assets/images/Matthew-Carter.jpg";
import Mikhail from "../assets/images/Mikhail-Bulgakov.jpg";

import Geo from "../assets/images/Geo.png";
import Lisa from "../assets/images/Lisa.png";
import Anne from "../assets/images/Anne.png";
import Flo from "../assets/images/Flo.png";

export const isLoginT = "loginT";
export const isLoginF = "loginF";

export const addItemsToCart = "addItemsToCart";
export const removeItemsFromCart = "removeItemsFromCart";
export const addItemsDuplicate = "addItemsDuplicate";

export const addBooksToCart = "addBooksToCart";
export const removeBooksFromCart = "removeBooksFromCart";
export const addBooksDuplicate = "addBooksDuplicate";

export const menuArr = [
  "Books",
  "Authors",
  "What to Read?",
  "Gift Ideas",
  "About Us",
];

export const ArrayBestSellers = [
  {
    id: "0001",
    image: AfterDark,
    author: "Murakami",
    title: "After Dark",
    comments: 5,
    star: 4.0,
    people: 100,
    price: "$15.5",
    salePrice: "10.50",
  },

  {
    image: Godfather,
    id: "0002",
    author: "Mario Puzo",
    title: "The Godfather",
    comments: 15,
    star: 4.9,
    people: 85,
    salePrice: "14.50",
  },
  {
    image: BeyondTheSun,
    id: "0003",
    author: "Daniel Cargallo",
    title: "She Beyond Sun",
    comments: 14,
    star: 4.6,
    people: 165,
    price: "$19.50",
    salePrice: "15.00",
  },
  {
    image: IAmErik,
    id: "0004",
    author: "Erik Spiekermann",
    title: "Hello I am Erik",
    comments: 25,
    star: 4.5,
    people: 120,
    price: "@15.50",
    salePrice: "10.50",
  },
  {
    image: Ness,
    id: "0005",
    author: "Patrick Ness",
    title: "More Than This",
    comments: 42,
    star: 4.4,
    people: 48,
    salePrice: "20.00",
  },
  {
    image: Memoirs,
    id: "0006",
    author: "C.R. Brunt",
    title: "From the Memoirs of a Non-Enemy",
    comments: 25,
    star: 4.5,
    people: 120,
    salePrice: "16.50",
  },
  { title: "SEE ALL" },
  {
    image: Master,
    id: "0007",
    author: "Mikhail Bulgakov",
    title: "The Master & Margarita",
    comments: 35,
    star: 4.3,
    people: 30,
    salePrice: "10.50",
  },
  {
    image: Norman,
    id: "0008",
    author: "Donald Norman",
    title: "The Design of Everyday Things",
    comments: 28,
    star: 4.2,
    people: 20,
    salePrice: "9.50",
  },
];

export const authorsArray = [
  {
    image: Fyodor,
    author: "Fyodor Dostoyevskiy",
    book: "20 books",
  },
  {
    image: Erik,
    author: "Erik Spiekermann",
    book: "5 books",
  },
  {
    image: Zola,
    author: "Zola Neale Hurston",
    book: "16 books",
  },
  {
    image: Zola,
    author: "Toni Morrison",
    book: "11 books",
  },
  {
    image: Don,
    author: "Walter Isaacson",
    book: "12 books",
  },
  {
    image: JK,
    author: "Stephen King",
    book: "65 books",
  },
  {
    image: Matthew,
    author: "Malcolm Gladwell",
    book: "7 books",
  },
  {
    image: Mikhail,
    author: "Leo Tolstoy",
    book: "48 books",
  },
  { author: "SEE ALL" },
  {
    image: Don,
    author: "Don Norman",
    book: "6 books",
  },
  {
    image: JK,
    author: "JK Rowling",
    book: "16 books",
  },
  {
    image: Matthew,
    author: "Matthew Carter",
    book: "3 books",
  },
  {
    image: Mikhail,
    author: "Mikhail Bulgakov",
    book: "24 books",
  },
];

export const ArrayProducts = [
  {
    image: AfterDark,
    id: "0009",
    author: "Murakami",
    title: "After Dark",
    comments: 5,
    star: 3.0,
    people: 100,
    price: "$15.5",
    salePrice: "$10.50",
    type: "novel",
    publishDate: "May 2007",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: "Rib Knits",
  },
  {
    image: Godfather,
    id: "0010",
    author: "Mario Puzo",
    title: "The Godfather",
    comments: 15,
    star: 4.9,
    people: 85,
    salePrice: "$14.50",
    type: "novel",
    publishDate: "May 2007",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: "Rib Knits",
  },
  {
    image: BeyondTheSun,
    id: "0011",
    author: "Daniel Cargallo",
    title: "She Beyond Sun",
    comments: 14,
    star: 4.6,
    people: 165,
    price: "$19.50",
    salePrice: "$15.00",
    type: "novel",
    publishDate: "May 2007",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: "Panne Velvet",
  },
  {
    image: IAmErik,
    id: "0012",
    author: "Erik Spiekermann",
    title: "Hello I am Erik",
    comments: 25,
    star: 4.5,
    people: 120,
    price: "$15.50",
    salePrice: "$10.50",
    type: "novel",
    publishDate: "May 2007",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: "Elasticized Fabrics",
  },
  {
    image: Ness,
    id: "0013",
    author: "Patrick Ness",
    title: "More Than This",
    comments: 42,
    star: 4.4,
    people: 48,
    salePrice: "$20.00",
    type: "novel",
    publishDate: "May 2007",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: " Dotted Swiss",
  },
  {
    image: IAmErik,
    id: "0014",
    author: "Erik Spiekermann",
    title: "Hello I am Erik",
    comments: 25,
    star: 4.5,
    people: 120,
    price: "$15.50",
    salePrice: "$10.50",
    type: "novel",
    publishDate: "May 2007",
    language: "Russian",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: " Dotted Swiss",
  },
  {
    image: Ness,
    id: "0015",
    author: "Patrick Ness",
    title: "More Than This",
    comments: 42,
    star: 4.4,
    people: 48,
    salePrice: "$20.00",
    type: "novel",
    publishDate: "May 2006",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: "Elasticized Fabrics",
  },
  {
    image: Memoirs,
    id: "0016",
    author: "C.R. Brunt",
    title: "From the Memoirs of a Non-Enemy",
    comments: 25,
    star: 4.5,
    people: 120,
    salePrice: "$16.50",
    type: "novel",
    publishDate: "May 2007",
    language: "Russian",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: "Elasticized Fabrics",
  },
  {
    image: Master,
    id: "0017",
    author: "Mikhail Bulgakov",
    title: "The Master & Margarita",
    comments: 35,
    star: 4.0,
    people: 30,
    salePrice: "$10.50",
    type: "novel",
    publishDate: "May 2007",
    language: "Russian",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: "Panne Velvet",
  },
  {
    image: Norman,
    id: "0018",
    author: "Donald Norman",
    title: "The Design of Everyday Things",
    comments: 28,
    star: 3.2,
    people: 20,
    salePrice: "$9.50",
    type: "novel",
    publishDate: "May 2005",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Softcover",
    publisher: "Panne Velvet",
  },
  {
    image: IAmErik,
    id: "0019",
    author: "Erik Spiekermann",
    title: "Hello I am Erik",
    comments: 25,
    star: 4.5,
    people: 120,
    price: "$15.50",
    salePrice: "$10.50",
    type: "novel",
    publishDate: "May 2008",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Softcover",
    publisher: "Panne Velvet",
  },
  {
    image: Ness,
    id: "0020",
    author: "Patrick Ness",
    title: "More Than This",
    comments: 42,
    star: 2.4,
    people: 48,
    salePrice: "$20.00",
    type: "novel",
    publishDate: "May 2006",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Softcover",
    publisher: "Double Knit",
  },
  {
    image: IAmErik,
    id: "0012",
    author: "Erik Spiekermann",
    title: "Hello I am Erik",
    comments: 25,
    star: 4.5,
    people: 120,
    price: "$15.50",
    salePrice: "$10.50",
    type: "novel",
    publishDate: "May 2007",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: "Elasticized Fabrics",
  },
  {
    image: AfterDark,
    id: "BK-001",
    author: "Haruki Murakami",
    title: "After Dark (Standard)",
    comments: 12,
    star: 4.2,
    people: 210,
    price: "$18.00",
    salePrice: "$12.99",
    type: "Mystery",
    publishDate: "May 2007",
    language: "English",
    pages: 208,
    readTime: "5 hours",
    cover: "Hardcover",
    publisher: "Vintage Books",
  },
  {
    image: Godfather,
    id: "BK-002",
    author: "Mario Puzo",
    title: "The Godfather: Legacy",
    comments: 85,
    star: 4.9,
    people: 1200,
    price: "$22.50",
    salePrice: "$14.50",
    type: "Crime",
    publishDate: "March 1969",
    language: "English",
    pages: 448,
    readTime: "12 hours",
    cover: "Paperback",
    publisher: "Putnam",
  },
  {
    image: BeyondTheSun,
    id: "BK-003",
    author: "D. Cargallo",
    title: "Beyond The Sun",
    comments: 22,
    star: 4.6,
    people: 165,
    price: "$19.50",
    salePrice: "$15.00",
    type: "Sci-Fi",
    publishDate: "June 2015",
    language: "Spanish",
    pages: 310,
    readTime: "8 hours",
    cover: "Digital",
    publisher: "Galaxia",
  },
  {
    image: IAmErik,
    id: "BK-004",
    author: "Erik Spiekermann",
    title: "Typography Mastery",
    comments: 45,
    star: 4.8,
    people: 340,
    price: "$45.00",
    salePrice: "$38.00",
    type: "Design",
    publishDate: "Jan 2014",
    language: "German",
    pages: 250,
    readTime: "4 hours",
    cover: "Hardcover",
    publisher: "Gestalten",
  },
  {
    image: Ness,
    id: "BK-005",
    author: "Patrick Ness",
    title: "The Chaos Walking",
    comments: 104,
    star: 4.7,
    people: 890,
    price: "$25.00",
    salePrice: "$20.00",
    type: "YA Fiction",
    publishDate: "Sept 2008",
    language: "English",
    pages: 400,
    readTime: "10 hours",
    cover: "Softcover",
    publisher: "Walker Books",
  },
  {
    image: Memoirs,
    id: "BK-006",
    author: "C.R. Brunt",
    title: "The Non-Enemy Memoirs",
    comments: 8,
    star: 3.9,
    people: 45,
    price: "$16.50",
    salePrice: "$14.00",
    type: "Biography",
    publishDate: "Nov 2020",
    language: "Russian",
    pages: 512,
    readTime: "15 hours",
    cover: "Hardcover",
    publisher: "Siberian Press",
  },
  {
    image: Master,
    id: "BK-007",
    author: "M. Bulgakov",
    title: "Margarita's Secret",
    comments: 67,
    star: 5.0,
    people: 400,
    price: "$15.00",
    salePrice: "$10.50",
    type: "Classic",
    publishDate: "Original 1967",
    language: "Russian",
    pages: 384,
    readTime: "9 hours",
    cover: "Hardcover",
    publisher: "YMCA Press",
  },
  {
    image: Norman,
    id: "BK-008",
    author: "Don Norman",
    title: "Psychology of Objects",
    comments: 200,
    star: 4.9,
    people: 5000,
    price: "$20.00",
    salePrice: "$16.20",
    type: "Non-Fiction",
    publishDate: "Oct 1988",
    language: "English",
    pages: 352,
    readTime: "7 hours",
    cover: "Softcover",
    publisher: "Basic Books",
  },
  // REPEATING IMAGES WITH NEW DATA
  {
    image: AfterDark,
    id: "BK-009",
    author: "H. Murakami",
    title: "After Dark: Special Ed.",
    comments: 3,
    star: 3.5,
    people: 12,
    price: "$30.00",
    salePrice: "$25.00",
    type: "Limited",
    publishDate: "May 2024",
    language: "Japanese",
    pages: 210,
    readTime: "5 hours",
    cover: "Leatherbound",
    publisher: "Shinchosha",
  },
  {
    image: Godfather,
    id: "BK-010",
    author: "Mario Puzo",
    title: "The Sicilian Connection",
    comments: 12,
    star: 4.1,
    people: 90,
    price: "$14.00",
    salePrice: "$11.00",
    type: "Crime",
    publishDate: "1984",
    language: "Italian",
    pages: 400,
    readTime: "11 hours",
    cover: "Softcover",
    publisher: "Random House",
  },
  {
    image: Ness,
    id: "0013",
    author: "Patrick Ness",
    title: "More Than This",
    price: "$14",
    comments: 42,
    star: 4.4,
    people: 48,
    salePrice: "$20.00",
    type: "novel",
    publishDate: "May 2007",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: " Dotted Swiss",
  },
  {
    image: IAmErik,
    id: "0014",
    author: "Erik Spiekermann",
    title: "Hello I am Erik",
    comments: 25,
    star: 4.5,
    people: 120,
    price: "$15.50",
    salePrice: "$10.50",
    type: "novel",
    publishDate: "May 2007",
    language: "Russian",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: " Dotted Swiss",
  },
  {
    image: Ness,
    id: "0015",
    author: "Patrick Ness",
    title: "More Than This",
    comments: 42,
    star: 4.4,
    people: 48,
    salePrice: "$20.00",
    type: "novel",
    publishDate: "May 2006",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: "Elasticized Fabrics",
  },
  {
    image: Memoirs,
    id: "0016",
    author: "C.R. Brunt",
    title: "From the Memoirs of a Non-Enemy",
    comments: 25,
    star: 4.5,
    people: 120,
    salePrice: "$16.50",
    type: "novel",
    publishDate: "May 2007",
    language: "Russian",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: "Elasticized Fabrics",
  },
  {
    image: Master,
    id: "0017",
    author: "Mikhail Bulgakov",
    title: "The Master & Margarita",
    comments: 35,
    star: 4.0,
    people: 30,
    salePrice: "$10.50",
    type: "novel",
    publishDate: "May 2007",
    language: "Russian",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Hardcover",
    publisher: "Panne Velvet",
  },
  {
    image: Norman,
    id: "0018",
    author: "Donald Norman",
    title: "The Design of Everyday Things",
    comments: 28,
    star: 3.2,
    people: 20,
    salePrice: "$9.50",
    type: "novel",
    publishDate: "May 2005",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Softcover",
    publisher: "Panne Velvet",
  },
  {
    image: IAmErik,
    id: "0019",
    author: "Erik Spiekermann",
    title: "Hello I am Erik",
    comments: 25,
    star: 4.5,
    people: 120,
    price: "$15.50",
    salePrice: "$10.50",
    type: "novel",
    publishDate: "May 2008",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Softcover",
    publisher: "Panne Velvet",
  },
  {
    image: Ness,
    id: "0020",
    author: "Patrick Ness",
    title: "More Than This",
    comments: 42,
    star: 2.4,
    people: 48,
    salePrice: "$20.00",
    type: "novel",
    publishDate: "May 2006",
    language: "English",
    pages: 208,
    readTime: "4-6 hours",
    cover: "Softcover",
    publisher: "Double Knit",
  },
];

export const suggestionArray = [
  {
    image: AfterDark,
    author: "Murakami",
    title: "After Dark",
  },
  {
    image: Godfather,
    author: "Mario Puzo",
    title: "The Godfather",
  },
  {
    image: BeyondTheSun,
    author: "Daniel Cargallo",
    title: "She Beyond Sun",
  },
  {
    image: IAmErik,
    author: "Erik Spiekermann",
    title: "Hello I am Erik",
  },
  {
    image: Ness,
    author: "Patrick Ness",
    title: "More Than This",
  },
  {
    image: IAmErik,
    author: "Erik Spiekermann",
    title: "Hello I am Erik",
  },
];

export const customerReviewArray = [
  {
    image: Geo,
    name: "Geoffrey Mott",
    date: "11 october 2025",
    rating: "4",
    review:
      "Muscle by Alan Trotter is a fresh piece of noir fiction. Our main characters are the two crooks Box and _____. They are on the hunt for odd jobs that most of us, hopefully, would not be willing to fulfill. It felt reminiscent of both A Clockwork Orange and The Time Machine. I guess that can seem like a strange combination, but Alan Trotter made it work.When Box and _____. encounter a private detective and this strange writer, events quickly start to unravel. Oh, and there is a girl of course! Ixsas",
  },
  {
    image: Lisa,
    name: "Lisa Anderson",
    date: "11 november 2025",
    rating: "2",
    review:
      "Oh I really disliked this in the end. What middling interest I had was completely lost by the fifth and last section.This is the story of two tough guys, goons for hire, as they pick up odd jobs roughing up guys, collecting debts and breaking hands. All written as a kind of Chandler pastiche, but possibly more of a parody.One of the goons, Box, passes the time reading sci-fi stories from pulp magazines an acquaintance writes for. Then, as the story progresses and the pair's jobs take a dark turn",
  },
  {
    image: Anne,
    name: "Anne Powell",
    date: "12 october 2025",
    rating: "3",
    review:
      "Read a great review in the Guardian and took a chance. I should have paid more attention to the comparison with The New York Trilogy, my least favourite Auster experience.This does noir tropes really well with women always called “twists” or “frails”, but I wasn’t really on board for the final section where it all gets a bit meta. I’m down for literary noir, but this was no Motherless Brooklyn.",
  },
  {
    image: Flo,
    name: "Florencio Dorrance",
    date: "11 december 2025",
    rating: "5",
    review:
      "This is fantastic, and could have been written just for me. Grimly funny absurdist-existentialist noir that incorporates pulp sci-fi as well as hardboiled crime fiction elements to become a surprisingly powerful examination of the lasting impact of male violence in its many forms.It also does one of my favourite things, which is to recount other fictional stories within its own pages, a Vonnegut-style technique I never seem to tire of. The ending, too, which some have complained about, I think works perfectly.Phenomenally entertaining and sneakily profound.",
  },
];

export const id = () => {
  const alphabet = [
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
  ];

  let id = "";
  let check = false;
  for (let i = 0; id.length < 8; i++) {
    let element = Math.floor(Math.random() * 10);
    if (!check) {
      if (element % 2 !== 0) {
        for (let i = 0; i < 3; i++) {
          element = alphabet[Math.floor(Math.random() * 10)];
          id += element;
          if (i === 2) {
            check = true;
          }
        }
      }
    } else {
      id = id + String(+element);
    }
  }
  return id;
};
